### ISSUE TITLE
Search and replace string value

### ISSUE THREAD

**Issue by GermanAizek** [ac3ss0r/ZMemory#2]
@ac3ss0r, Is there search and replacement ASCII and Unicode strings?

**Comment by JustCoolDev** [comment]
Hi bro ! I'm currently making an mod of this project on my GitHub. You can watch my project to see the future functions :) Have a nice day

**Comment by GermanAizek** [comment]
> Hi bro ! I'm currently making an mod of this project on my GitHub. You can watch my project to see the future functions :) Have a nice day

Many thanks for activity in fork https://github.com/JustCoolDev/ZMemory-mod
